# Generated by Django 5.1 on 2024-09-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="course",
            field=models.CharField(default="Course", max_length=100),
            preserve_default=False,
        ),
    ]
