# Generated by Django 5.1 on 2024-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="short_title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
