# Generated by Django 5.1 on 2024-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_short_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="short_title",
            field=models.CharField(max_length=100),
        ),
    ]
