# Generated by Django 5.1 on 2024-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fee", models.IntegerField()),
                ("level", models.CharField(max_length=100)),
                ("enrolled", models.IntegerField()),
                ("duration", models.CharField(max_length=100)),
                ("provided_by", models.CharField(max_length=100)),
                (
                    "requirements",
                    models.JSONField(default=list, help_text="List of requirements"),
                ),
                (
                    "material_includes",
                    models.JSONField(
                        default=list,
                        help_text="List of materials included in the course",
                    ),
                ),
                (
                    "audience",
                    models.JSONField(
                        default=list, help_text="Target audience for the course"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of tags associated with the course",
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list,
                        help_text="List of learning objectives or outcomes",
                    ),
                ),
                (
                    "daily_schedule",
                    models.JSONField(
                        default=dict,
                        help_text="Time at which the course is held each day",
                    ),
                ),
                (
                    "brief_description",
                    models.TextField(
                        help_text="Brief description explaining who this course is for"
                    ),
                ),
                (
                    "course_description",
                    models.TextField(help_text="Detailed course description"),
                ),
                (
                    "additional_description",
                    models.TextField(help_text="Additional details about the course"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Categories associated with the course",
                        related_name="courses",
                        to="courses.category",
                    ),
                ),
            ],
        ),
    ]
