# Generated by Django 5.1 on 2024-08-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tutor",
            field=models.CharField(default="Mufti Bilal Sabir", max_length=100),
        ),
    ]
