# Generated by Django 5.1 on 2024-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tutor",
            field=models.CharField(max_length=100),
        ),
    ]
