# Generated by Django 5.1 on 2024-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="enrolled",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
