# Generated by Django 5.1 on 2024-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_enrolled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="daily_schedule",
        ),
        migrations.AddField(
            model_name="course",
            name="class_days",
            field=models.JSONField(
                default=list, help_text="List of days of the week the course is offered"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="class_time",
            field=models.TimeField(default="07:00:00"),
        ),
    ]
