# Generated by Django 5.1 on 2024-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_daily_schedule_course_class_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
