# Generated by Django 5.1 on 2024-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
