# Generated by Django 5.1 on 2024-09-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="class_time",
        ),
    ]
