# Generated by Django 5.1 on 2024-09-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_course_class_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="duration",
            new_name="total_duration",
        ),
    ]
