# Generated by Django 5.1 on 2024-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_rename_duration_course_total_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="class_duration",
            field=models.CharField(default="1 hour", max_length=100),
        ),
    ]
