# Generated by Django 5.1 on 2024-09-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_course_class_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Plan 1", "2 Days (Mon & Wed)"),
                            ("Plan 2", "2 Days (Sat & Sun)"),
                            ("Plan 3", "3 Days (Mon, Wed & Fri)"),
                            ("Plan 4", "5 Days (Mon to Fri)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("number_of_classes_per_week", models.IntegerField()),
                (
                    "class_days",
                    models.JSONField(
                        default=list, help_text="Days of the week for this plan"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
