# Generated by Django 5.1 on 2024-09-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_courseplan_fee_alter_courseplan_class_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="fee",
        ),
    ]
