# Generated by Django 5.1 on 2024-09-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_remove_course_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseplan",
            name="class_days",
            field=models.CharField(default="Mon & Wed"),
        ),
        migrations.AlterField(
            model_name="courseplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("Plan 1", "2 Days (Mon & Wed)"),
                    ("Plan 2 (Weekend Classes)", "2 Days (Sat & Sun)"),
                    ("Plan 3", "3 Days (Mon, Wed & Fri)"),
                    ("Plan 4", "5 Days (Mon to Fri)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
